from __future__ import annotations

import smtplib
from collections import defaultdict
from datetime import datetime
from email.message import EmailMessage
from html import escape

from .config import AppConfig
from .models import FeedEntry


def _format_when(ts: datetime | None) -> str:
    if not ts:
        return "Unknown date"
    return ts.strftime("%Y-%m-%d %H:%M UTC")


def _format_authors(authors: list[str]) -> str:
    if not authors:
        return "Authors: Unknown"
    if len(authors) <= 10:
        return "Authors: " + ", ".join(authors)

    lead = authors[:3]
    tail = authors[-3:]
    hidden_count = len(authors) - len(lead) - len(tail)
    return "Authors: " + ", ".join(lead) + f", ... ({hidden_count} omitted), " + ", ".join(tail)


def _article_type_sort_key(article_type: str) -> tuple[int, str]:
    normalized = article_type.strip().lower()
    priority = {
        "article": 0,
        "research articles": 0,
        "reports": 1,
        "reviews": 2,
        "perspectives": 3,
        "policy forum": 4,
        "editorials": 5,
        "letters": 6,
        "technical comments": 7,
        "news": 8,
        "news features": 9,
        "news focus": 10,
        "careers": 11,
        "books et al.": 12,
        "review": 13,
        "letter": 14,
        "editorial": 15,
        "news feature": 16,
        "nature briefing": 17,
        "news in brief": 18,
        "news & views": 19,
        "research highlight": 20,
        "research highlights": 21,
        "opinion": 22,
        "correspondence": 23,
        "scientific correspondence": 24,
        "matters arising": 25,
        "book review": 26,
        "books & arts": 27,
        "books received": 28,
        "obituary": 29,
        "miscellany": 30,
        "author correction": 31,
        "publisher correction": 32,
        "erratum": 33,
        "perspective": 34,
        "commentary": 35,
        "other": 50,
    }
    return (priority.get(normalized, 50), normalized)


class EmailNotifier:
    def __init__(self, config: AppConfig) -> None:
        self.config = config

    def _build_plain_text(self, entries: list[FeedEntry]) -> str:
        grouped: dict[str, dict[str, list[FeedEntry]]] = defaultdict(lambda: defaultdict(list))
        for entry in entries:
            grouped[entry.feed_title][entry.article_type].append(entry)

        lines = [f"New publications found: {len(entries)}", ""]
        for feed_title in sorted(grouped):
            journal_total = sum(len(items) for items in grouped[feed_title].values())
            lines.append(f"{feed_title} ({journal_total})")
            for article_type in sorted(grouped[feed_title], key=_article_type_sort_key):
                lines.append(f"  {article_type} ({len(grouped[feed_title][article_type])})")
                for item in grouped[feed_title][article_type]:
                    lines.append(f"- {item.title}")
                    lines.append(f"  {_format_authors(item.authors)}")
                    lines.append(f"  {_format_when(item.published)}")
            lines.append("")

        lines.append("This message was generated by your RSS notifier.")
        return "\n".join(lines)

    def _build_html(self, entries: list[FeedEntry]) -> str:
        grouped: dict[str, dict[str, list[FeedEntry]]] = defaultdict(lambda: defaultdict(list))
        for entry in entries:
            grouped[entry.feed_title][entry.article_type].append(entry)

        parts = [
            "<html><body>",
            f"<p><strong>New publications found: {len(entries)}</strong></p>",
        ]

        for feed_title in sorted(grouped):
            journal_total = sum(len(items) for items in grouped[feed_title].values())
            parts.append(f"<h2>{escape(feed_title)} ({journal_total})</h2>")
            for article_type in sorted(grouped[feed_title], key=_article_type_sort_key):
                parts.append(
                    f"<h3>{escape(article_type)} ({len(grouped[feed_title][article_type])})</h3>"
                )
                parts.append("<ul>")
                for item in grouped[feed_title][article_type]:
                    safe_title = escape(item.title)
                    safe_link = escape(item.link)
                    safe_authors = escape(_format_authors(item.authors))
                    safe_when = escape(_format_when(item.published))

                    if item.link:
                        title_html = f'<a href="{safe_link}">{safe_title}</a>'
                    else:
                        title_html = safe_title

                    parts.append("<li>")
                    parts.append(f"<div><strong>{title_html}</strong></div>")
                    parts.append(f"<div>{safe_authors}</div>")
                    parts.append(f"<div>{safe_when}</div>")
                    parts.append("</li>")
                parts.append("</ul>")

        parts.append("<p>This message was generated by your RSS notifier.</p>")
        parts.append("</body></html>")
        return "".join(parts)

    def send_digest(self, entries: list[FeedEntry]) -> None:
        if not entries:
            return

        if self.config.dry_run:
            print(self._build_plain_text(entries))
            return

        self.config.validate_email_settings()

        message = EmailMessage()
        message["From"] = self.config.smtp_from
        message["To"] = ", ".join(self.config.notify_to)
        message["Subject"] = f"{self.config.subject_prefix} {len(entries)} new publication(s)"
        message.set_content(self._build_plain_text(entries))
        message.add_alternative(self._build_html(entries), subtype="html")

        with smtplib.SMTP(self.config.smtp_host, self.config.smtp_port, timeout=30) as smtp:
            if self.config.smtp_use_tls:
                smtp.starttls()
            if self.config.smtp_username:
                smtp.login(self.config.smtp_username, self.config.smtp_password)
            smtp.send_message(message)
